import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./_layout/header";

export const metadata: Metadata = {
  title: "Ford-Byte",
  description: "Generated by Ford-Byte",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex">
        <Header />
        <main className="flex-grow">{children}</main>
      </body>
    </html>
  );
}
